/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin1

import kotlin.test.Test
import kotlin.test.assertSame

class AppTest {
    @Test fun `app should download URL concurrently and reliably`() {
        assertSame(true, false, "Can you figure out a proper test for that?")
    }
}
